### ISSUE TITLE
objective-0.6.3.3 doesn't compile with elevator 0.2

### ISSUE THREAD

**Issue by peti** [fumieval/objective#3]
The build log is at http://hydra.cryp.to/build/522897/nixlog/1/raw. Would it be possible to get a new release for this package that supports the [latest versions of its dependencies](http://packdeps.haskellers.com/feed?needle=objective)?

**Comment by peti** [comment]
Ping? Did you see this issue?

**Comment by fumieval** [comment]
Sorry for not responding in a timely manner, I've fixed and just uploaded 0.6.5.
